services:
  - type: web
    name: vagasta-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    repo: https://github.com/Jphood888/Vagasta-downloader
    branch: main
