services:
  - type: web
    name: vagasta-downloader
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    repo: https://github.com/Jphood888/Vagasta-downloader
    branch: main
    plan: free
